package repofacts

import (
	"path/filepath"
	"regexp"
	"sort"
	"strings"

	"github.com/makifbaysal/tasktrooper/server/internal/application/dotnet"
)

// maxDotnetProjects bounds how many project files one profile reports. A
// solution with 120 projects is real, but a profile listing all of them is a
// directory listing, and the solution line already names the build.
const maxDotnetProjects = 40

// dotnetFrameworkPackages are the NuGet packages worth naming in a profile,
// matched as a prefix (Microsoft.EntityFrameworkCore.SqlServer counts as EF
// Core). As with frameworkDeps, these decide how code is written; the rest is
// the lockfile's business.
var dotnetFrameworkPackages = []string{
	"Microsoft.EntityFrameworkCore", "Dapper", "Npgsql", "MongoDB.Driver", "StackExchange.Redis",
	"MediatR", "MassTransit", "RabbitMQ.Client", "Confluent.Kafka", "Hangfire", "Quartz",
	"FluentValidation", "AutoMapper", "Mapster", "Serilog", "OpenTelemetry", "Polly",
	"Swashbuckle", "Microsoft.AspNetCore.OpenApi", "Scalar.AspNetCore", "Grpc.AspNetCore",
	"Microsoft.AspNetCore.SignalR", "Microsoft.AspNetCore.Authentication.JwtBearer", "Duende.IdentityServer",
	"Aspire.", "Microsoft.Orleans", "Akka",
	"xunit", "NUnit", "MSTest", "FluentAssertions", "Shouldly", "NSubstitute", "Moq", "FakeItEasy",
	"Testcontainers", "Microsoft.AspNetCore.Mvc.Testing", "Bogus", "Verify.", "coverlet.collector",
}

// dotnetTestMarkers make a project a test project even when it does not set
// <IsTestProject>: any of these references means `dotnet test` has something
// to run in it.
var dotnetTestMarkers = []string{"Microsoft.NET.Test.Sdk", "xunit", "NUnit", "MSTest", "TUnit"}

var (
	csprojSdkRe       = regexp.MustCompile(`<Project[^>]*\sSdk="([^"]+)"`)
	csprojFrameworkRe = regexp.MustCompile(`<TargetFrameworks?>([^<]+)</TargetFrameworks?>`)
	csprojPackageRe   = regexp.MustCompile(`<PackageReference[^>]*\sInclude="([^"]+)"(?:[^>]*\sVersion="([^"]+)")?`)
	csprojTestFlagRe  = regexp.MustCompile(`<IsTestProject>\s*true\s*</IsTestProject>`)
	globalSDKRe       = regexp.MustCompile(`"sdk"\s*:\s*\{[^}]*"version"\s*:\s*"([^"]+)"`)
)

// collectDotnet reports solutions, projects and the pinned SDK, and derives
// the build/test/run commands from them. Everything under a Unity project is
// skipped: its .csproj/.sln files are regenerated by the editor and are not a
// dotnet CLI build.
func collectDotnet(root string, t *treeScan, f *Facts) {
	unityRoots := unityProjectRoots(t)
	inUnity := func(rel string) bool {
		for _, u := range unityRoots {
			if u == "" || strings.HasPrefix(rel, u+"/") {
				return true
			}
		}
		return false
	}

	var solutions, projects []string
	for _, rel := range t.files {
		if inUnity(rel) {
			continue
		}
		base := filepath.Base(rel)
		switch {
		case dotnet.IsSolutionFile(base) && depth(rel) <= 2:
			solutions = append(solutions, rel)
		case dotnet.IsProjectFile(base) && depth(rel) <= 4:
			projects = append(projects, rel)
		}
	}
	sort.Strings(solutions)
	sort.Strings(projects)
	if len(solutions) == 0 && len(projects) == 0 {
		return
	}

	for _, p := range t.find("global.json") {
		if depth(p) > 2 || inUnity(p) {
			continue
		}
		raw, err := readCapped(filepath.Join(root, p))
		if err != nil {
			continue
		}
		if m := globalSDKRe.FindSubmatch(raw); m != nil {
			f.Manifests = append(f.Manifests, Manifest{Path: p, Ecosystem: "dotnet", Manager: "dotnet sdk", Version: "sdk " + string(m[1])})
		}
	}

	for _, sln := range solutions {
		f.Manifests = append(f.Manifests, Manifest{
			Path: sln, Ecosystem: "dotnet", Manager: "nuget",
			Name: strings.TrimSuffix(filepath.Base(sln), filepath.Ext(sln)),
		})
		area, file := dirOf(sln), filepath.Base(sln)
		f.Commands = append(f.Commands,
			Command{Purpose: "build", Area: area, Cmd: "dotnet build " + file, Source: sln},
			Command{Purpose: "test", Area: area, Cmd: "dotnet test " + file, Source: sln},
		)
		if t.has(join(area, ".editorconfig")) {
			f.Commands = append(f.Commands, Command{Purpose: "lint", Area: area, Cmd: "dotnet format " + file + " --verify-no-changes", Source: join(area, ".editorconfig")})
		}
	}

	if len(projects) > maxDotnetProjects {
		f.Warnings = append(f.Warnings, "only the first "+itoa(maxDotnetProjects)+" of "+itoa(len(projects))+" .NET projects are profiled")
		projects = projects[:maxDotnetProjects]
	}
	for _, proj := range projects {
		info, ok := readDotnetProject(root, proj)
		if !ok {
			f.Warnings = append(f.Warnings, "could not read "+proj)
			continue
		}
		f.Manifests = append(f.Manifests, info.manifest)
		area, file := dirOf(proj), filepath.Base(proj)
		// With a solution the solution line already builds and tests every
		// project; per-project lines would only repeat it.
		if len(solutions) == 0 {
			if info.test {
				f.Commands = append(f.Commands, Command{Purpose: "test", Area: area, Cmd: "dotnet test " + file, Source: proj})
			} else {
				f.Commands = append(f.Commands, Command{Purpose: "build", Area: area, Cmd: "dotnet build " + file, Source: proj})
			}
		}
		if info.runnable {
			f.Commands = append(f.Commands, Command{Purpose: "run", Area: area, Cmd: "dotnet run --project " + file, Source: proj})
		}
		if info.efCore && !info.test {
			f.Commands = append(f.Commands, Command{Purpose: "migrate", Area: area, Cmd: "dotnet ef database update --project " + file, Source: proj})
		}
	}
}

type dotnetProjectInfo struct {
	manifest Manifest
	test     bool
	runnable bool
	efCore   bool
}

func readDotnetProject(root, rel string) (dotnetProjectInfo, bool) {
	raw, err := readCapped(filepath.Join(root, rel))
	if err != nil {
		return dotnetProjectInfo{}, false
	}
	body := string(raw)
	m := Manifest{
		Path: rel, Ecosystem: "dotnet", Manager: "nuget",
		Name: strings.TrimSuffix(filepath.Base(rel), filepath.Ext(rel)),
	}
	if fm := csprojFrameworkRe.FindStringSubmatch(body); fm != nil {
		m.Version = strings.TrimSpace(fm[1])
	}
	sdk := ""
	if sm := csprojSdkRe.FindStringSubmatch(body); sm != nil {
		sdk = sm[1]
		if sdk != "Microsoft.NET.Sdk" {
			m.Deps = append(m.Deps, "sdk:"+sdk)
		}
	}

	info := dotnetProjectInfo{test: csprojTestFlagRe.MatchString(body)}
	for _, pm := range csprojPackageRe.FindAllStringSubmatch(body, -1) {
		name, version := pm[1], pm[2]
		for _, marker := range dotnetTestMarkers {
			if strings.HasPrefix(name, marker) {
				info.test = true
			}
		}
		if strings.HasPrefix(name, "Microsoft.EntityFrameworkCore") {
			info.efCore = true
		}
		if !hasPrefixAny(name, dotnetFrameworkPackages) {
			continue
		}
		if version != "" {
			m.Deps = append(m.Deps, name+"@"+version)
		} else {
			m.Deps = append(m.Deps, name)
		}
	}
	sort.Strings(m.Deps)
	info.manifest = m
	info.runnable = !info.test && (strings.HasPrefix(sdk, "Microsoft.NET.Sdk.Web") ||
		strings.HasPrefix(sdk, "Microsoft.NET.Sdk.Worker") ||
		strings.Contains(body, "<OutputType>Exe</OutputType>"))
	return info, true
}

// unityProjectRoots are the repo-relative directories ("" for the root) that
// hold a Unity project.
func unityProjectRoots(t *treeScan) []string {
	var out []string
	for _, p := range t.find("ProjectVersion.txt") {
		dir := dirOf(p)
		if filepath.Base(dir) != "ProjectSettings" {
			continue
		}
		out = append(out, dirOf(dir))
	}
	return out
}

func hasPrefixAny(s string, prefixes []string) bool {
	for _, p := range prefixes {
		if strings.HasPrefix(s, p) {
			return true
		}
	}
	return false
}
