package pipeline

// The workflows below are WRAPPERS. Checkout, toolchain, call the script —
// and nothing that is not also in the script, because a step that exists only
// under Actions is a step a local run silently skips.
//
// Three things legitimately live here rather than in the script, and each is
// something a shell script cannot do for itself:
//
//   - the dispatch form (which channel, and Android's two onboarding knobs),
//   - the runner image and the toolchain it needs installed,
//   - `upload-artifact`, which is how a produced build becomes downloadable.
//
// Everything else — signing, building, exporting, uploading, promoting,
// masking — is in the script.

const iosWorkflowBody = `# GENERATED by agent-server (application/storeops/pipeline). Edit the
# generator, not this file.
#
# A WRAPPER. Every step of the release lives in
#   @SCRIPTPATH@
# so this run and a run from a paired Mac do the same thing. A step added here
# would exist only under Actions, and the copy nobody watches is always the one
# that drifts.
name: mobile-release

on:
  workflow_dispatch:
    inputs:
      channel:
        description: "stage = build and upload to TestFlight; prod = submit the tested build for App Store review (no rebuild)"
        type: choice
        options: [stage, prod]
        default: stage

# Keyed on the APP, not the repository: two apps in one monorepo release
# independently, and two runs against the same app must never race for one
# build number or one App Store Connect submission. Not cancelled in flight —
# a half-uploaded binary is worse than a queued run.
concurrency:
  group: mobile-${{ inputs.channel }}-@IDENTIFIER@
  cancel-in-progress: false

jobs:
  release:
    # Apple's toolchain exists nowhere else.
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4

      # macos images ship fastlane, but prod is the one channel that cannot
      # proceed without it, so it is made certain there rather than assumed.
      - if: inputs.channel == 'prod'
        run: gem install fastlane --no-document

      - name: Release
        # Everything reaches the script through the ENVIRONMENT. ${{ }} inside
        # a run: block is textual substitution into the shell line, and the
        # only reason it would be safe here is that channel is a choice input —
        # which is not a property to depend on the next time an input is added.
        env:
          CHANNEL: ${{ inputs.channel }}
          BUILD_NUMBER: ${{ github.run_number }}
          IOS_DIST_CERT_P12: ${{ secrets.IOS_DIST_CERT_P12 }}
          IOS_CERT_PASSWORD: ${{ secrets.IOS_CERT_PASSWORD }}
          IOS_PROFILE_B64: ${{ secrets.IOS_PROFILE_B64 }}
          ASC_KEY_ID: ${{ secrets.ASC_KEY_ID }}
          ASC_ISSUER_ID: ${{ secrets.ASC_ISSUER_ID }}
          ASC_KEY_P8: ${{ secrets.ASC_KEY_P8 }}
        # Invoked through bash explicitly: the file is generated 0755 with a
        # bash shebang, and this is the second guard on the one mistake that
        # cost a day (see the script's own header).
        run: bash @SCRIPTPATH@ "$CHANNEL"

      # The one thing the script cannot do for itself: make what it produced
      # downloadable. always(), because the script writes the signed build
      # BEFORE attempting an upload — which is the whole first-publish path,
      # where the store has no app record yet and the binary goes up by hand.
      - if: always()
        uses: actions/upload-artifact@v4
        with:
          name: mobile-release-@IDENTIFIER@
          path: @ARTIFACTSGLOB@
          if-no-files-found: ignore
`

const androidWorkflowBody = `# GENERATED by agent-server (application/storeops/pipeline). Edit the
# generator, not this file.
#
# A WRAPPER. Every step of the release lives in
#   @SCRIPTPATH@
# so this run and a run from a paired Mac do the same thing. A step added here
# would exist only under Actions, and the copy nobody watches is always the one
# that drifts.
name: mobile-release

on:
  workflow_dispatch:
    inputs:
      channel:
        description: "stage = build a signed AAB and upload to Internal testing; prod = promote internal to production (no rebuild)"
        type: choice
        options: [stage, prod]
        default: stage
      upload:
        description: "Upload to the internal track. Set false for a brand-new app: Play only accepts its FIRST bundle by hand, and the run's artifact is what you upload."
        type: boolean
        default: true
      rollout:
        description: "Production staged rollout fraction (prod only)"
        type: string
        default: "0.2"

# Keyed on the APP, not the repository: two apps in one monorepo release
# independently, and two runs against the same app must never race for one
# versionCode or one Play track. Not cancelled in flight — a half-uploaded
# bundle is worse than a queued run.
concurrency:
  group: mobile-${{ inputs.channel }}-@IDENTIFIER@
  cancel-in-progress: false

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2"

      # fastlane supply is how the script talks to Play on BOTH channels.
      - run: gem install fastlane --no-document

      - name: Release
        # Everything reaches the script through the ENVIRONMENT. ${{ }} inside
        # a run: block is textual substitution into the shell line, and the
        # only reason it would be safe here is that channel is a choice input —
        # which is not a property to depend on the next time an input is added.
        env:
          CHANNEL: ${{ inputs.channel }}
          BUILD_NUMBER: ${{ github.run_number }}
          MOBILE_RELEASE_UPLOAD: ${{ inputs.upload }}
          PLAY_ROLLOUT_FRACTION: ${{ inputs.rollout }}
          ANDROID_UPLOAD_KEYSTORE_B64: ${{ secrets.ANDROID_UPLOAD_KEYSTORE_B64 }}
          ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
          ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
          PLAY_SA_JSON: ${{ secrets.PLAY_SA_JSON }}
        # Invoked through bash explicitly: the file is generated 0755 with a
        # bash shebang, and this is the second guard on the one mistake that
        # cost a day (see the script's own header).
        run: bash @SCRIPTPATH@ "$CHANNEL"

      # The one thing the script cannot do for itself: make what it produced
      # downloadable. always(), because the script writes the signed bundle
      # BEFORE attempting an upload — which is the whole first-publish path,
      # where Play refuses the first AAB over the API and it goes up by hand.
      - if: always()
        uses: actions/upload-artifact@v4
        with:
          name: mobile-release-@IDENTIFIER@
          path: @ARTIFACTSGLOB@
          if-no-files-found: ignore
`

func iosWorkflow(s Spec) string {
	return expand(iosWorkflowBody,
		"@SCRIPTPATH@", s.runFromRoot(),
		"@IDENTIFIER@", s.Identifier,
		"@ARTIFACTSGLOB@", s.artifactsGlob(),
	)
}

func androidWorkflow(s Spec) string {
	return expand(androidWorkflowBody,
		"@SCRIPTPATH@", s.runFromRoot(),
		"@IDENTIFIER@", s.Identifier,
		"@ARTIFACTSGLOB@", s.artifactsGlob(),
	)
}
