#!/usr/bin/env bash
# Runs the backend (with its embedded Postgres) and the UI dev server side by
# side for contributors who want a browser and a terminal instead of the
# desktop app. Ctrl-C stops both.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SERVER_DIR="$ROOT/server"
UI_DIR="$ROOT/desktop/ui"
ENV_FILE="$SERVER_DIR/.env.local"

if [[ ! -f "$ENV_FILE" ]]; then
  cat > "$ENV_FILE" <<EOF
# Generated by scripts/dev.sh. Safe to edit; gitignored.
SERVER_API_KEY=local-dev-key
MCP_SECRETS_KEY=$(openssl rand -base64 32)
PORT=8085
DATA_DIR=$SERVER_DIR/data
EOF
  echo "wrote $ENV_FILE"
fi

set -a
# shellcheck disable=SC1090
source "$ENV_FILE"
set +a

if [[ ! -d "$UI_DIR/node_modules" ]]; then
  echo "UI dependencies missing — run: make setup" >&2
  exit 1
fi

cleanup() {
  trap - INT TERM EXIT
  [[ -n "${UI_PID:-}" ]] && kill "$UI_PID" 2>/dev/null || true
  [[ -n "${SERVER_PID:-}" ]] && kill "$SERVER_PID" 2>/dev/null || true
  wait 2>/dev/null || true
}
trap cleanup INT TERM EXIT

(cd "$SERVER_DIR" && go run ./cmd/agent-server) &
SERVER_PID=$!

(cd "$UI_DIR" && VITE_API_KEY="$SERVER_API_KEY" VITE_API_BASE="http://127.0.0.1:${PORT}" npm run dev) &
UI_PID=$!

echo
echo "backend: http://127.0.0.1:${PORT}   ui: http://localhost:3200   (Ctrl-C stops both)"
wait -n "$SERVER_PID" "$UI_PID"
