-- Undo 114: drop the policies, then drop the column.
--
-- `DROP COLUMN tenant_id CASCADE` takes every key that leads with it, which is
-- every unique key in the schema after 114 - so this leaves a schema with NO
-- uniqueness on agents.name, board_columns.slug, repositories.root_path or
-- board_tasks(task_type, task_number). It is a *structural* undo, not a
-- restoration: the pre-114 constraints are not put back, because putting them
-- back would fail the moment two tenants' rows are still in the table.
--
-- The same CASCADE takes the 82 composite FOREIGN KEYS of section 4b and the
-- 21 UNIQUE (tenant_id, id) constraints they reference, and those are not put
-- back either. So the undone schema has no referential integrity between its
-- tables at all - not merely weaker keys, none. That is a second reason this
-- is only ever an EMPTY-database operation.
--
-- No explicit DROP CONSTRAINT is needed for any of it: CASCADE from the parent
-- side reaches the children's FKs, and Postgres resolves the order. The one
-- thing to know while reading it is that the statements below therefore do
-- much more than their text says.
--
-- In other words this down migration is for a failed rollout on an EMPTY
-- database. On a database that has served two tenants there is no way back:
-- the data is interleaved and the only honest recovery is a restore. Said out
-- loud here rather than discovered at 3am.
DROP POLICY IF EXISTS tenant_isolation ON agent_cli_connection;
ALTER TABLE agent_cli_connection NO FORCE ROW LEVEL SECURITY;
ALTER TABLE agent_cli_connection DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON agent_column_subscriptions;
ALTER TABLE agent_column_subscriptions NO FORCE ROW LEVEL SECURITY;
ALTER TABLE agent_column_subscriptions DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON agent_evolution_events;
ALTER TABLE agent_evolution_events NO FORCE ROW LEVEL SECURITY;
ALTER TABLE agent_evolution_events DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON agent_golden_results;
ALTER TABLE agent_golden_results NO FORCE ROW LEVEL SECURITY;
ALTER TABLE agent_golden_results DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON agent_golden_tasks;
ALTER TABLE agent_golden_tasks NO FORCE ROW LEVEL SECURITY;
ALTER TABLE agent_golden_tasks DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON agent_kpi_results;
ALTER TABLE agent_kpi_results NO FORCE ROW LEVEL SECURITY;
ALTER TABLE agent_kpi_results DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON agent_kpis;
ALTER TABLE agent_kpis NO FORCE ROW LEVEL SECURITY;
ALTER TABLE agent_kpis DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON agent_memories;
ALTER TABLE agent_memories NO FORCE ROW LEVEL SECURITY;
ALTER TABLE agent_memories DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON agent_performance_scores;
ALTER TABLE agent_performance_scores NO FORCE ROW LEVEL SECURITY;
ALTER TABLE agent_performance_scores DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON agent_reflections;
ALTER TABLE agent_reflections NO FORCE ROW LEVEL SECURITY;
ALTER TABLE agent_reflections DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON agent_score_events;
ALTER TABLE agent_score_events NO FORCE ROW LEVEL SECURITY;
ALTER TABLE agent_score_events DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON agent_templates;
ALTER TABLE agent_templates NO FORCE ROW LEVEL SECURITY;
ALTER TABLE agent_templates DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON agents;
ALTER TABLE agents NO FORCE ROW LEVEL SECURITY;
ALTER TABLE agents DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON api_keys;
ALTER TABLE api_keys NO FORCE ROW LEVEL SECURITY;
ALTER TABLE api_keys DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON app_settings;
ALTER TABLE app_settings NO FORCE ROW LEVEL SECURITY;
ALTER TABLE app_settings DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON attachments;
ALTER TABLE attachments NO FORCE ROW LEVEL SECURITY;
ALTER TABLE attachments DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON audit_logs;
ALTER TABLE audit_logs NO FORCE ROW LEVEL SECURITY;
ALTER TABLE audit_logs DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON billing_plan;
ALTER TABLE billing_plan NO FORCE ROW LEVEL SECURITY;
ALTER TABLE billing_plan DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON board_column_transitions;
ALTER TABLE board_column_transitions NO FORCE ROW LEVEL SECURITY;
ALTER TABLE board_column_transitions DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON board_columns;
ALTER TABLE board_columns NO FORCE ROW LEVEL SECURITY;
ALTER TABLE board_columns DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON board_events;
ALTER TABLE board_events NO FORCE ROW LEVEL SECURITY;
ALTER TABLE board_events DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON board_members;
ALTER TABLE board_members NO FORCE ROW LEVEL SECURITY;
ALTER TABLE board_members DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON board_settings;
ALTER TABLE board_settings NO FORCE ROW LEVEL SECURITY;
ALTER TABLE board_settings DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON board_task_counters;
ALTER TABLE board_task_counters NO FORCE ROW LEVEL SECURITY;
ALTER TABLE board_task_counters DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON board_tasks;
ALTER TABLE board_tasks NO FORCE ROW LEVEL SECURITY;
ALTER TABLE board_tasks DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON catalog_versions;
ALTER TABLE catalog_versions NO FORCE ROW LEVEL SECURITY;
ALTER TABLE catalog_versions DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON deploy_dispatches;
ALTER TABLE deploy_dispatches NO FORCE ROW LEVEL SECURITY;
ALTER TABLE deploy_dispatches DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON deploy_package_tasks;
ALTER TABLE deploy_package_tasks NO FORCE ROW LEVEL SECURITY;
ALTER TABLE deploy_package_tasks DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON deploy_packages;
ALTER TABLE deploy_packages NO FORCE ROW LEVEL SECURITY;
ALTER TABLE deploy_packages DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON deployment_runs;
ALTER TABLE deployment_runs NO FORCE ROW LEVEL SECURITY;
ALTER TABLE deployment_runs DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON file_chunks;
ALTER TABLE file_chunks NO FORCE ROW LEVEL SECURITY;
ALTER TABLE file_chunks DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON files;
ALTER TABLE files NO FORCE ROW LEVEL SECURITY;
ALTER TABLE files DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON jobs;
ALTER TABLE jobs NO FORCE ROW LEVEL SECURITY;
ALTER TABLE jobs DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON live_activity_tokens;
ALTER TABLE live_activity_tokens NO FORCE ROW LEVEL SECURITY;
ALTER TABLE live_activity_tokens DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON llm_endpoint_secrets;
ALTER TABLE llm_endpoint_secrets NO FORCE ROW LEVEL SECURITY;
ALTER TABLE llm_endpoint_secrets DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON llm_endpoints;
ALTER TABLE llm_endpoints NO FORCE ROW LEVEL SECURITY;
ALTER TABLE llm_endpoints DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON llm_provider_configs;
ALTER TABLE llm_provider_configs NO FORCE ROW LEVEL SECURITY;
ALTER TABLE llm_provider_configs DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON llm_provider_secrets;
ALTER TABLE llm_provider_secrets NO FORCE ROW LEVEL SECURITY;
ALTER TABLE llm_provider_secrets DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON llm_usage;
ALTER TABLE llm_usage NO FORCE ROW LEVEL SECURITY;
ALTER TABLE llm_usage DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON mcp_server_secrets;
ALTER TABLE mcp_server_secrets NO FORCE ROW LEVEL SECURITY;
ALTER TABLE mcp_server_secrets DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON mcp_servers;
ALTER TABLE mcp_servers NO FORCE ROW LEVEL SECURITY;
ALTER TABLE mcp_servers DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON mobile_devices;
ALTER TABLE mobile_devices NO FORCE ROW LEVEL SECURITY;
ALTER TABLE mobile_devices DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON mobile_store_apps;
ALTER TABLE mobile_store_apps NO FORCE ROW LEVEL SECURITY;
ALTER TABLE mobile_store_apps DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON model_prices;
ALTER TABLE model_prices NO FORCE ROW LEVEL SECURITY;
ALTER TABLE model_prices DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON ops_audit_log;
ALTER TABLE ops_audit_log NO FORCE ROW LEVEL SECURITY;
ALTER TABLE ops_audit_log DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON orchestration_plans;
ALTER TABLE orchestration_plans NO FORCE ROW LEVEL SECURITY;
ALTER TABLE orchestration_plans DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON orchestrator_rules;
ALTER TABLE orchestrator_rules NO FORCE ROW LEVEL SECURITY;
ALTER TABLE orchestrator_rules DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON plan_tasks;
ALTER TABLE plan_tasks NO FORCE ROW LEVEL SECURITY;
ALTER TABLE plan_tasks DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON prod_incident_events;
ALTER TABLE prod_incident_events NO FORCE ROW LEVEL SECURITY;
ALTER TABLE prod_incident_events DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON prod_incidents;
ALTER TABLE prod_incidents NO FORCE ROW LEVEL SECURITY;
ALTER TABLE prod_incidents DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON projects;
ALTER TABLE projects NO FORCE ROW LEVEL SECURITY;
ALTER TABLE projects DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON push_devices;
ALTER TABLE push_devices NO FORCE ROW LEVEL SECURITY;
ALTER TABLE push_devices DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON quota_paused_tasks;
ALTER TABLE quota_paused_tasks NO FORCE ROW LEVEL SECURITY;
ALTER TABLE quota_paused_tasks DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON repositories;
ALTER TABLE repositories NO FORCE ROW LEVEL SECURITY;
ALTER TABLE repositories DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON repository_deploy_targets;
ALTER TABLE repository_deploy_targets NO FORCE ROW LEVEL SECURITY;
ALTER TABLE repository_deploy_targets DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON repository_hosting_links;
ALTER TABLE repository_hosting_links NO FORCE ROW LEVEL SECURITY;
ALTER TABLE repository_hosting_links DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON repository_pipeline_jobs;
ALTER TABLE repository_pipeline_jobs NO FORCE ROW LEVEL SECURITY;
ALTER TABLE repository_pipeline_jobs DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON repository_profile_proposals;
ALTER TABLE repository_profile_proposals NO FORCE ROW LEVEL SECURITY;
ALTER TABLE repository_profile_proposals DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON repository_profile_sections;
ALTER TABLE repository_profile_sections NO FORCE ROW LEVEL SECURITY;
ALTER TABLE repository_profile_sections DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON repository_projects;
ALTER TABLE repository_projects NO FORCE ROW LEVEL SECURITY;
ALTER TABLE repository_projects DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON session_actions;
ALTER TABLE session_actions NO FORCE ROW LEVEL SECURITY;
ALTER TABLE session_actions DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON session_message_attachments;
ALTER TABLE session_message_attachments NO FORCE ROW LEVEL SECURITY;
ALTER TABLE session_message_attachments DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON session_messages;
ALTER TABLE session_messages NO FORCE ROW LEVEL SECURITY;
ALTER TABLE session_messages DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON session_runs;
ALTER TABLE session_runs NO FORCE ROW LEVEL SECURITY;
ALTER TABLE session_runs DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON session_steps;
ALTER TABLE session_steps NO FORCE ROW LEVEL SECURITY;
ALTER TABLE session_steps DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON sessions;
ALTER TABLE sessions NO FORCE ROW LEVEL SECURITY;
ALTER TABLE sessions DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON signing_assets;
ALTER TABLE signing_assets NO FORCE ROW LEVEL SECURITY;
ALTER TABLE signing_assets DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON skills;
ALTER TABLE skills NO FORCE ROW LEVEL SECURITY;
ALTER TABLE skills DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON store_credentials;
ALTER TABLE store_credentials NO FORCE ROW LEVEL SECURITY;
ALTER TABLE store_credentials DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON task_acceptance_criteria;
ALTER TABLE task_acceptance_criteria NO FORCE ROW LEVEL SECURITY;
ALTER TABLE task_acceptance_criteria DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON task_agent_runs;
ALTER TABLE task_agent_runs NO FORCE ROW LEVEL SECURITY;
ALTER TABLE task_agent_runs DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON task_attachments;
ALTER TABLE task_attachments NO FORCE ROW LEVEL SECURITY;
ALTER TABLE task_attachments DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON task_column_spans;
ALTER TABLE task_column_spans NO FORCE ROW LEVEL SECURITY;
ALTER TABLE task_column_spans DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON task_comments;
ALTER TABLE task_comments NO FORCE ROW LEVEL SECURITY;
ALTER TABLE task_comments DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON task_criterion_checks;
ALTER TABLE task_criterion_checks NO FORCE ROW LEVEL SECURITY;
ALTER TABLE task_criterion_checks DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON task_documents;
ALTER TABLE task_documents NO FORCE ROW LEVEL SECURITY;
ALTER TABLE task_documents DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON task_pipeline_jobs;
ALTER TABLE task_pipeline_jobs NO FORCE ROW LEVEL SECURITY;
ALTER TABLE task_pipeline_jobs DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON task_pipelines;
ALTER TABLE task_pipelines NO FORCE ROW LEVEL SECURITY;
ALTER TABLE task_pipelines DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON task_relations;
ALTER TABLE task_relations NO FORCE ROW LEVEL SECURITY;
ALTER TABLE task_relations DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON workspace_chunks;
ALTER TABLE workspace_chunks NO FORCE ROW LEVEL SECURITY;
ALTER TABLE workspace_chunks DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON workspace_edges;
ALTER TABLE workspace_edges NO FORCE ROW LEVEL SECURITY;
ALTER TABLE workspace_edges DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON workspace_file_hashes;
ALTER TABLE workspace_file_hashes NO FORCE ROW LEVEL SECURITY;
ALTER TABLE workspace_file_hashes DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON workspace_indexes;
ALTER TABLE workspace_indexes NO FORCE ROW LEVEL SECURITY;
ALTER TABLE workspace_indexes DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON workspace_symbols;
ALTER TABLE workspace_symbols NO FORCE ROW LEVEL SECURITY;
ALTER TABLE workspace_symbols DISABLE ROW LEVEL SECURITY;

ALTER TABLE agent_cli_connection DROP COLUMN IF EXISTS tenant_id CASCADE;
ALTER TABLE agent_column_subscriptions DROP COLUMN IF EXISTS tenant_id CASCADE;
ALTER TABLE agent_evolution_events DROP COLUMN IF EXISTS tenant_id CASCADE;
ALTER TABLE agent_golden_results DROP COLUMN IF EXISTS tenant_id CASCADE;
ALTER TABLE agent_golden_tasks DROP COLUMN IF EXISTS tenant_id CASCADE;
ALTER TABLE agent_kpi_results DROP COLUMN IF EXISTS tenant_id CASCADE;
ALTER TABLE agent_kpis DROP COLUMN IF EXISTS tenant_id CASCADE;
ALTER TABLE agent_memories DROP COLUMN IF EXISTS tenant_id CASCADE;
ALTER TABLE agent_performance_scores DROP COLUMN IF EXISTS tenant_id CASCADE;
ALTER TABLE agent_reflections DROP COLUMN IF EXISTS tenant_id CASCADE;
ALTER TABLE agent_score_events DROP COLUMN IF EXISTS tenant_id CASCADE;
ALTER TABLE agent_templates DROP COLUMN IF EXISTS tenant_id CASCADE;
ALTER TABLE agents DROP COLUMN IF EXISTS tenant_id CASCADE;
ALTER TABLE api_keys DROP COLUMN IF EXISTS tenant_id CASCADE;
ALTER TABLE app_settings DROP COLUMN IF EXISTS tenant_id CASCADE;
ALTER TABLE attachments DROP COLUMN IF EXISTS tenant_id CASCADE;
ALTER TABLE audit_logs DROP COLUMN IF EXISTS tenant_id CASCADE;
ALTER TABLE billing_plan DROP COLUMN IF EXISTS tenant_id CASCADE;
ALTER TABLE board_column_transitions DROP COLUMN IF EXISTS tenant_id CASCADE;
ALTER TABLE board_columns DROP COLUMN IF EXISTS tenant_id CASCADE;
ALTER TABLE board_events DROP COLUMN IF EXISTS tenant_id CASCADE;
ALTER TABLE board_members DROP COLUMN IF EXISTS tenant_id CASCADE;
ALTER TABLE board_settings DROP COLUMN IF EXISTS tenant_id CASCADE;
ALTER TABLE board_task_counters DROP COLUMN IF EXISTS tenant_id CASCADE;
ALTER TABLE board_tasks DROP COLUMN IF EXISTS tenant_id CASCADE;
ALTER TABLE catalog_versions DROP COLUMN IF EXISTS tenant_id CASCADE;
ALTER TABLE deploy_dispatches DROP COLUMN IF EXISTS tenant_id CASCADE;
ALTER TABLE deploy_package_tasks DROP COLUMN IF EXISTS tenant_id CASCADE;
ALTER TABLE deploy_packages DROP COLUMN IF EXISTS tenant_id CASCADE;
ALTER TABLE deployment_runs DROP COLUMN IF EXISTS tenant_id CASCADE;
ALTER TABLE file_chunks DROP COLUMN IF EXISTS tenant_id CASCADE;
ALTER TABLE files DROP COLUMN IF EXISTS tenant_id CASCADE;
ALTER TABLE jobs DROP COLUMN IF EXISTS tenant_id CASCADE;
ALTER TABLE live_activity_tokens DROP COLUMN IF EXISTS tenant_id CASCADE;
ALTER TABLE llm_endpoint_secrets DROP COLUMN IF EXISTS tenant_id CASCADE;
ALTER TABLE llm_endpoints DROP COLUMN IF EXISTS tenant_id CASCADE;
ALTER TABLE llm_provider_configs DROP COLUMN IF EXISTS tenant_id CASCADE;
ALTER TABLE llm_provider_secrets DROP COLUMN IF EXISTS tenant_id CASCADE;
ALTER TABLE llm_usage DROP COLUMN IF EXISTS tenant_id CASCADE;
ALTER TABLE mcp_server_secrets DROP COLUMN IF EXISTS tenant_id CASCADE;
ALTER TABLE mcp_servers DROP COLUMN IF EXISTS tenant_id CASCADE;
ALTER TABLE mobile_devices DROP COLUMN IF EXISTS tenant_id CASCADE;
ALTER TABLE mobile_store_apps DROP COLUMN IF EXISTS tenant_id CASCADE;
ALTER TABLE model_prices DROP COLUMN IF EXISTS tenant_id CASCADE;
ALTER TABLE ops_audit_log DROP COLUMN IF EXISTS tenant_id CASCADE;
ALTER TABLE orchestration_plans DROP COLUMN IF EXISTS tenant_id CASCADE;
ALTER TABLE orchestrator_rules DROP COLUMN IF EXISTS tenant_id CASCADE;
ALTER TABLE plan_tasks DROP COLUMN IF EXISTS tenant_id CASCADE;
ALTER TABLE prod_incident_events DROP COLUMN IF EXISTS tenant_id CASCADE;
ALTER TABLE prod_incidents DROP COLUMN IF EXISTS tenant_id CASCADE;
ALTER TABLE projects DROP COLUMN IF EXISTS tenant_id CASCADE;
ALTER TABLE push_devices DROP COLUMN IF EXISTS tenant_id CASCADE;
ALTER TABLE quota_paused_tasks DROP COLUMN IF EXISTS tenant_id CASCADE;
ALTER TABLE repositories DROP COLUMN IF EXISTS tenant_id CASCADE;
ALTER TABLE repository_deploy_targets DROP COLUMN IF EXISTS tenant_id CASCADE;
ALTER TABLE repository_hosting_links DROP COLUMN IF EXISTS tenant_id CASCADE;
ALTER TABLE repository_pipeline_jobs DROP COLUMN IF EXISTS tenant_id CASCADE;
ALTER TABLE repository_profile_proposals DROP COLUMN IF EXISTS tenant_id CASCADE;
ALTER TABLE repository_profile_sections DROP COLUMN IF EXISTS tenant_id CASCADE;
ALTER TABLE repository_projects DROP COLUMN IF EXISTS tenant_id CASCADE;
ALTER TABLE session_actions DROP COLUMN IF EXISTS tenant_id CASCADE;
ALTER TABLE session_message_attachments DROP COLUMN IF EXISTS tenant_id CASCADE;
ALTER TABLE session_messages DROP COLUMN IF EXISTS tenant_id CASCADE;
ALTER TABLE session_runs DROP COLUMN IF EXISTS tenant_id CASCADE;
ALTER TABLE session_steps DROP COLUMN IF EXISTS tenant_id CASCADE;
ALTER TABLE sessions DROP COLUMN IF EXISTS tenant_id CASCADE;
ALTER TABLE signing_assets DROP COLUMN IF EXISTS tenant_id CASCADE;
ALTER TABLE skills DROP COLUMN IF EXISTS tenant_id CASCADE;
ALTER TABLE store_credentials DROP COLUMN IF EXISTS tenant_id CASCADE;
ALTER TABLE task_acceptance_criteria DROP COLUMN IF EXISTS tenant_id CASCADE;
ALTER TABLE task_agent_runs DROP COLUMN IF EXISTS tenant_id CASCADE;
ALTER TABLE task_attachments DROP COLUMN IF EXISTS tenant_id CASCADE;
ALTER TABLE task_column_spans DROP COLUMN IF EXISTS tenant_id CASCADE;
ALTER TABLE task_comments DROP COLUMN IF EXISTS tenant_id CASCADE;
ALTER TABLE task_criterion_checks DROP COLUMN IF EXISTS tenant_id CASCADE;
ALTER TABLE task_documents DROP COLUMN IF EXISTS tenant_id CASCADE;
ALTER TABLE task_pipeline_jobs DROP COLUMN IF EXISTS tenant_id CASCADE;
ALTER TABLE task_pipelines DROP COLUMN IF EXISTS tenant_id CASCADE;
ALTER TABLE task_relations DROP COLUMN IF EXISTS tenant_id CASCADE;
ALTER TABLE workspace_chunks DROP COLUMN IF EXISTS tenant_id CASCADE;
ALTER TABLE workspace_edges DROP COLUMN IF EXISTS tenant_id CASCADE;
ALTER TABLE workspace_file_hashes DROP COLUMN IF EXISTS tenant_id CASCADE;
ALTER TABLE workspace_indexes DROP COLUMN IF EXISTS tenant_id CASCADE;
ALTER TABLE workspace_symbols DROP COLUMN IF EXISTS tenant_id CASCADE;
